
source 'https://github.com/wsl2ls/SLSpecs.git' #私有索引库
source 'https://github.com/CocoaPods/Specs.git'  #公有索引库

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SwiftStudy' do
  use_frameworks!
  # 忽略引入库的所有警告
  inhibit_all_warnings!
  
  pod 'SnapKit'
  pod 'Alamofire', '~> 4.8'
  pod 'AlamofireImage', '~> 3.5'
  pod 'Kingfisher', '~> 5.5.0'
  pod 'HandyJSON', '~> 5.0.0'
  pod 'GDPerformanceView-Swift', '~> 2.0.2'
  
  pod 'WKWebView'  #私有组件索引
  
end


