# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SwiftStudy' do
  use_frameworks!
  # 忽略引入库的所有警告
  inhibit_all_warnings!
  
  pod 'SnapKit'
  pod 'Alamofire', '~> 4.8'
  pod 'AlamofireImage', '~> 3.5'
  pod 'Kingfisher', '~> 5.5.0'
  
end


